### ISSUE TITLE
Custom Requests

### ISSUE THREAD

**Issue by kdeenanauth** [go-humble/rest#5]
Is it possible to initiate custom requests that are not RESTful?

**Comment by albrow** [comment]
@kdeenanauth unfortunately this library cannot be all things for all people. I want to keep it focused on RESTful requests.

There is already some level of customizability via the `RootURL` and `ModelId` methods of the [`rest.Model` interface](https://godoc.org/github.com/go-humble/rest#Model). If that does not offer you enough customizability, the best option may be to write the code yourself. You are more than welcome to look at this library for examples. In case you didn't know, you can use the builtin [http package](https://golang.org/pkg/net/http/) with GopherJS (perhaps with some limitations). So sending requests is pretty straightforward.

If you copy substantial parts of the code in this repo I just ask that you follow the [license](https://github.com/go-humble/rest/blob/master/LICENSE). Of course, you are also free to start from scratch.

Hope that helps!

**Comment by kdeenanauth** [comment]
That's cool and I appreciate the specific goals of the humble projects.

I've found https://github.com/PalmStoneGames/gopherjs-net-http which reimplements `net/http` to avoid the large file sizes as well.

**Comment by albrow** [comment]
👌 I'm going to close this issue. Feel free to re-open if you have any more questions.
